name: Deploy windows version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Clone GitLab Repository
      run: |
        git clone --depth 1 https://${{ secrets.GITLAB_USER }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/oktoworkspace/application.git
        cd application
        git checkout main
        git pull
        npm install
        npm run build:win
